Separación de Helpers, Comandos y Servicios HTTP; Implementación del Patrón Strategy
gophers-latam/challenges pull request #13
Opened 2024-06-12 03:59 UTC by dcdeve

Este PR introduce una serie de cambios significativos en la estructura del proyecto para mejorar la modularidad, mantenibilidad y escalabilidad del código. A continuación se detallan los cambios realizados:

1. **Separación de Helpers, Comandos y Servicios HTTP**:
    - Se crearon nuevas carpetas para `helpers`, `subcmd_commands` y `service_http` para organizar mejor el código y seguir las mejores prácticas de modularidad.
    - Cada carpeta contiene los archivos relacionados a su funcionalidad específica, facilitando la localización y el mantenimiento del código.

2. **Implementación del Patrón Strategy**:
    - Se refactorizó la lógica de manejo de comandos utilizando el patrón Strategy para hacer el código más extensible y fácil de mantener.
    - Cada comando ahora implementa la interfaz `Command` con métodos `Execute` y `Help`.

3. **Adaptación de Comandos Existentes**:
    - Todos los comandos existentes (`hours`, `challenge`, `events`, `facts`, `hello`) fueron adaptados a la nueva estructura.
    - Los métodos `Help` de cada comando fueron definidos en español para proporcionar instrucciones claras sobre el uso de cada comando.

4. **Uso de Helpers desde subcmd_commands**:
    - Los comandos ahora utilizan las funciones auxiliares definidas en la carpeta `helpers`, mejorando la reutilización del código.

5. **Actualización del Archivo go.mod**:
    - Se actualizó el archivo `go.mod` para reflejar los cambios en la estructura del proyecto y asegurar que las importaciones sean correctas.

### Estructura del Proyecto

/project-root
|-- /helpers
| |-- helpers.go
|-- /subcmd_commands
| |-- challenge_command.go
| |-- events_command.go
| |-- facts_command.go
| |-- hello_command.go
| |-- hours_command.go
|-- /service_http
| |-- service.go
|-- subcmd_router.go
|-- subcmd_init.go
|-- go.mod

### Detalles de Implementación

1. **Archivo: `helpers/helpers.go`**
   Define las funciones auxiliares, como `UnsuccessfulMsg`.

2. **Archivo: `subcmd_commands/hours_command.go`**
   Ejemplo de un comando adaptado para usar el paquete `helpers`.

3. **Archivo: `subcmd_init.go`**
   Inicializa el mapa `SubCmdCommands` y registra todos los comandos.

4. **Archivo: `subcmd_router.go`**
   Utiliza el mapa `SubCmdCommands` inicializado en `subcmd_init.go` y define la lógica para el enrutamiento de comandos.

### Beneficios

- **Modularidad**: La separación del código en distintas carpetas facilita la gestión y la escalabilidad del proyecto.
- **Mantenibilidad**: El uso del patrón Strategy y la organización del código permiten una mejor mantenibilidad y extensibilidad.
- **Claridad**: Las funciones auxiliares centralizadas en `helpers` y las instrucciones claras en los métodos `Help` mejoran la comprensión y el uso del bot.

### Pasos a Seguir

1. **Revisar los cambios**: Asegúrese de que la nueva estructura y las implementaciones se alineen con los objetivos del proyecto.
2. **Pruebas**: Pendiente
3. **Aprobación del PR**: Una vez verificado, apruebe y fusione el PR para aplicar las mejoras al proyecto.

2024-06-12 16:59 UTC, ThiagoMowszet commented
Se realizaron las pruebas funcionales y son optimas. 
En la codereview se detallaran los cambios a realizar.
💯 🖖

2024-06-12 17:13 UTC, zeroidentidad approved these changes
Se puede considerar que:
- Se tomara como referencia para estandarizar cambios
- Se supliran posteriormente los comentarios dejados en discord

2024-06-12 21:53 UTC, ThiagoMowszet requested changes
@dcdeve excelentes cambios! 
Aportan mucho al proyecto y simplifica mucho el futuro código para nuevas implementaciones. Lo testee y funciona muy bien, lo único que corregiría es lo que te marco en los comentarios.
Saludos. ️ 🎖️

2024-06-12 21:53 UTC, ThiagoMowszet commented on bot/subcmd_commands/challenge_command.go
> +	return "Uso: .go challenge {nivel} {tipo} - Pedir desafío para practicar.\n" +
>A comparación del anterior código de salida, me quedaría con el anterior. Ya que este no especifica los diferentes niveles y tipos de challenges que existen. Si entra alguien nuevo y lo quiere usar no va a saber que poner.
El anterior es mucho mas amigable y legible, dejo como se veía:

Para usar el bot de challenge, debes seguir esta sintaxis:
    .go challenge **_{nivel} {tipo_challenge}_**

Los niveles disponibles son: easy, medium, hard
Los tipos disponibles son: backend, algorithm, concurrency, database, web, cli, frontend

Podes subir el texto del challenge acá: https://gopherbot.onrender.com/


>Esto lo veo mucho mas practico y a parte deja la posibilidad a los usuarios de poder subir su challenge (esto se podria ser otro comando igualmente).

2024-06-12 21:53 UTC, ThiagoMowszet commented on bot/subcmd_commands/hours_command.go
> +	return "Uso: .go hours {HH:MM (formato 24h)} {país} - Muestra la hora en diferentes zonas horarias\n" +
Agregaria en:
>Uso: .go hours {HH:MM (formato 24h)} {país/**_emoticono de bandera_**} 


o algo similar para que el usuario tambien sepa que existen esta posibilidad.

2024-06-12 21:53 UTC, ThiagoMowszet commented on bot/subcmd_commands/events_command.go
> +	return "Uso: .go events - Listar eventos establecidos como recurrentes"
Corregiría el texto a:
"Uso: .go events - Lista los eventos recurrentes del servidor"

2024-06-13 00:09 UTC, ThiagoMowszet requested changes
Probe el de eventos y hours y estan bien!
En el de challenge faltaron los saltos de linea.

2024-06-13 00:09 UTC, ThiagoMowszet commented on bot/subcmd_commands/challenge_command.go
> +	return "Uso: .go challenge {nivel} {tipo_challenge} - Pedir desafío para practicar.\n" +
Veo lo siguiente cuando lo ejecuto:
![image](https://github.com/gophers-latam/challenges/assets/73196303/c78ccef4-4d3f-4020-b17c-70c1812b9736)

falta el \n en la linea 55 y 56.
También los `-` para cada punto, así se vería con los cambios:

![image](https://github.com/gophers-latam/challenges/assets/73196303/ca86e475-7ca5-479b-aa85-61e4a919b490)


y si queres, podemos agregarle a cada comando para que aparezca en negrita con:

> ** .go challenge {nivel} {tipo} - Pedir desafío para practicar **

![image](https://github.com/gophers-latam/challenges/assets/73196303/ebc9664d-096c-45b1-8458-1250516f7349)

2024-06-13 00:42 UTC, dcdeve commented
@ThiagoMowszet Listo.

Tambien hice un **fix para parsear las flags en HoursCommand**, **cambie FlagToCountry** para pasar las key a lower case haciendo una **comparacion  safe** y **removi la funcion WordCase**.

2024-06-13 01:31 UTC, ThiagoMowszet approved these changes
Buenisimo! gracias por la contribucion @dcdeve.
Esperamos mas aportes de tu parte 💯

2024-06-13 02:02 UTC, merged