chequeo de la palabra "bot"
gophers-latam/challenges pull request #7
Opened 2024-04-24 01:46 UTC by ThiagoMowszet

En esta PR, lo que se busca, es evitar que el bot aparezca cuando no es llamado.
Algunos casos de prueba fueron cuando se escribian palabras como "ro**bot**", "**bot**ella`,  "**bot**on", "**bot**onera" y el bot aparecia.

Evidencia:
![image](https://github.com/gophers-latam/challenges/assets/73196303/b30e91eb-cfaf-4ab1-8558-2bd0e1d3ccd5)

2024-04-24 02:10 UTC, zeroidentidad commented on bot/bot_subcmd.go
> -	if strings.Contains(m.Content, "bot") {
una posible era probar con espacios tipo: `"bot "` o para mas preciso con una regex y evitar los pasos de descomponer las cadena en fields y hacer el loop de busqueda.

probar solo cambiando:
`
if regexp.MatchString("\\bbot\\b", m.Content) {
...
}
`

2024-04-24 02:12 UTC, zeroidentidad requested changes
probar con lo comentado

2024-04-24 02:12 UTC, ThiagoMowszet commented on bot/bot_subcmd.go
> -	if strings.Contains(m.Content, "bot") {
Tenes razón! Mañana pruebo lo del regex.

2024-04-26 00:13 UTC, ThiagoMowszet commented
Se modificó la función, usando el paquete **_"regexp"_** para una mejor precisión, haciendo caso de los comentarios mencionados.

2024-04-26 13:22 UTC, zeroidentidad approved these changes
👍🏽

2024-04-26 13:22 UTC, merged